- name: Install fail2ban
  ansible.builtin.apt:
    pkg: fail2ban

- name: Config proxmox
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0640"
  loop:
    - src: pve/jail.conf
      dest: /etc/fail2ban/jail.d/pve.conf
    - src: pve/filter.conf
      dest: /etc/fail2ban/filter.d/pve.conf
  when: "'pve' in group_names"
  notify: Restart fail2ban
